name: Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: ['macos-latest']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run eslint

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 15.x]
        os: ['windows-latest', 'ubuntu-latest']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
